import addon.TapandGetToastMessage;
import io.appium.java_client.TouchAction;
import io.appium.java_client.touch.WaitOptions;
import io.appium.java_client.touch.offset.PointOption;
import io.testproject.sdk.drivers.ReportingDriver;
import java.lang.Exception;
import java.time.Duration;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.testng.annotations.Test;

/**
 * This class was automatically generated by TestProject
 * Project: +1 Город (Android)
 * Test: APPS-36 Появляется ошибка "не верный логин или пароль" при попытке авторизоваться по неверному логину и паролю
 * Generated by: Svyatoslav Novikov (snovikov@techranch.ru)
 * Generated on Wed Oct 20 13:53:35 GMT 2021.
 */

public class Apps36 extends BaseClass {

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @Test(description = "APPS-36 Появляется ошибка \"не верный логин или пароль\" при попытке авторизоваться по неверному логину и паролю")
  void apps36() throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    TapandGetToastMessage.TapAndGetToast tapAndGetToast;

    // 1. Reset App
    //    Clear application data and restart (Auto-generated)
    GeneratedUtils.sleep(500);
    driver.resetApp();

    // 2. Click 'Далее'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(120000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.id("com.poleznygorod.cityplusone:id/button_next");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 3. Click 'Далее'
    GeneratedUtils.sleep(500);
    by = By.id("com.poleznygorod.cityplusone:id/button_next");
    driver.findElement(by).click();

    // 4. Click 'Регистрация и вход'
    GeneratedUtils.sleep(500);
    by = By.id("com.poleznygorod.cityplusone:id/button_sign_up");
    driver.findElement(by).click();

    // 5. Make a Swipe gesture from ('770','1490') to ('753','496')
    GeneratedUtils.sleep(500);
    (new TouchAction(driver)).press(PointOption.point(770,1490))
        				.waitAction(WaitOptions.waitOptions(Duration.ofMillis(300)))
        				.moveTo(PointOption.point(753,496)).release().perform();

    // 6. Click 'Авторизация'
    GeneratedUtils.sleep(500);
    by = By.id("com.poleznygorod.cityplusone:id/switch_sign_type");
    driver.findElement(by).click();

    // 7. Click 'E-mail'
    GeneratedUtils.sleep(500);
    by = By.xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.EditText");
    driver.findElement(by).click();

    // 8. Type '{{TestLogin}}' in 'E-mail'
    GeneratedUtils.sleep(500);
    by = By.xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.EditText");
    driver.findElement(by).sendKeys(ProjectParameters.TestLogin);

    // 9. Click 'Пароль'
    GeneratedUtils.sleep(500);
    by = By.xpath("//android.widget.EditText[@text = 'Пароль']");
    driver.findElement(by).click();

    // 10. Type 'WrongPassword' in 'Пароль'
    GeneratedUtils.sleep(500);
    by = By.xpath("//android.widget.EditText[@text = 'Пароль']");
    driver.findElement(by).sendKeys("WrongPassword");

    // 11. Tapping on the element get toast text
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    tapAndGetToast = TapandGetToastMessage.getTapAndGetToast();
    by = By.id("com.poleznygorod.cityplusone:id/button_get_code");
    tapAndGetToast = (TapandGetToastMessage.TapAndGetToast)((ReportingDriver)driver).addons().execute(tapAndGetToast, by, -1);
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

  }
}
