/**
 * This class was automatically generated by TestProject
 * Adds a copy of project +1 Город (Android) parameters
 */
class ProjectParameters {
  /**
   *
   */
  public static String TestLogin = "test login here";

  /**
   * This was a SECRET parameter and therefore its value is empty
   */
  public static String TestPassword = "test password here";
}
